site:
    title:        FILLME
    description:  FILLME
    author_name:  Grégoire Pineau
    author_email: lyrixx@lyrixx.info
    author_url:   http://gregoirepineau.fr
    gh_url:       FILLME

engine:
    themes:
        - %dir%/vendor/lyrixx/my-theme-bootstrap
        - %dir%/vendor/carew/theme-bootstrap
    extensions:
        - Carew\Plugin\Toc\TocExtension
        - Carew\Plugin\Highlight\HighlightExtension
